- project:
    templates:
      - check-requirements
      - release-notes-jobs
      - openstack-python-jobs-horizon
      - openstack-python35-jobs-horizon
      - nodejs4-jobs
    check:
      jobs:
        - murano-dashboard-sanity-check

        - openstack-tox-cover:
            voting: false
            required-projects:
              - openstack/horizon
    post:
      jobs:
        - openstack-tox-cover:
            required-projects:
              - openstack/horizon
    experimental:
      jobs:
        - murano-dashboard-selenium-package

- job:
    name: murano-dashboard-sanity-check
    parent: legacy-dsvm-base
    run: playbooks/legacy/murano-dashboard-sanity-check/run.yaml
    post-run: playbooks/legacy/murano-dashboard-sanity-check/post.yaml
    voting: false
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/heat
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-heatclient
      - openstack/python-muranoclient
      - openstack/horizon
      - openstack/heat-dashboard

- job:
    name: murano-dashboard-selenium-package
    parent: legacy-dsvm-base
    run: playbooks/dashboard-dsvm-selenium-package/run.yaml
    post-run: playbooks/dashboard-dsvm-selenium-package/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/murano
      - openstack/murano-dashboard
      - openstack/python-muranoclient
